import Link from 'next/link';
import { Reveal, Stagger } from '@/components/reveal';

export default function PRDPage() {
  return <>
    <section className="page-hero"><div className="container"><Reveal><span className="eyebrow">05 · Product brief</span></Reveal><Reveal><h1>이 프로젝트가 필요한 이유를<br /><em>한 장의 PRD</em>로 정리합니다.</h1></Reveal><Reveal><p>서비스가 무엇을 만들고 무엇을 만들지 않는지, 어떤 사용자가 어떤 지표로 성공을 판단하는지 빠르게 훑을 수 있습니다.</p></Reveal></div></section>
    <section className="section"><div className="container"><div className="prd-grid"><article className="prd-card"><h3>문제</h3><p>현대백화점 점포·상품군마다 판매속도·보관·처리기한이 다른데, 하나의 할인율로 위험재고를 처리하면 실제 손실과 책임을 설명하기 어렵습니다.</p></article><article className="prd-card"><h3>1차 사용자</h3><p>자기 점포의 재고 상태와 비용을 알고 실행 결과에 책임지는 현대백화점 책임 MD입니다.</p></article><article className="prd-card"><h3>핵심 가치</h3><p>위험재고를 찾고, 기준선 대비 처리 대안을 비교하고, 담당자가 설명 가능한 근거로 승인하도록 돕습니다.</p></article><article className="prd-card"><h3>사람과 AI</h3><p>AI는 계산·비교·설명을 담당합니다. 가격·할인·수량·재고 변경은 권한 있는 사람이 승인합니다.</p></article><article className="prd-card"><h3>P1 포함 범위</h3><ul><li>더현대 서울 직매입 재고 위험 탐지</li><li>의류·신발 등 1~2개 상품군 우선 검증</li><li>할인·타임세일·아울렛·기부·폐기 비교</li><li>최대 3개 전략 후보·수식 시뮬레이션</li><li>승인·Teams 전달·실행 결과 회수</li></ul></article><article className="prd-card"><h3>P2 후순위</h3><ul><li>다른 현대백화점 점포 비교</li><li>점포 간 재고 이동·이동비·수신 용량</li><li>식품·가구·가전·특약·임대 확장</li><li>점포·채널 공동 프로모션</li></ul></article></div></div></section>
    <section className="section-tight band"><div className="container split"><div><span className="eyebrow">Success metrics</span><h2 className="section-heading" style={{marginTop: 14, marginBottom: 20}}>많이 파는 것이 아니라,<br />더 나은 결정을 측정합니다.</h2><p className="lead">위험재고 규모, 처리기한 내 예상 처리율, 기준선 대비 <Link href="/glossary#incremental-profit" className="inline-link">증분이익</Link>, 회피된 보관·폐기 비용, 예측 오차를 봅니다.</p></div><Stagger className="metric-grid"><div className="metric-card"><span className="eyebrow">Metric 01</span><span className="metric-value">처리율</span><p>기한 안에 위험재고가 얼마나 줄었는가</p></div><div className="metric-card"><span className="eyebrow">Metric 02</span><span className="metric-value">증분이익</span><p>기준선보다 얼마나 나아졌는가</p></div><div className="metric-card"><span className="eyebrow">Metric 03</span><span className="metric-value">오차</span><p>예측과 실행 결과의 차이는 얼마인가</p></div></Stagger></div></section>
  </>;
}
